### ISSUE TITLE
STDOUT is not displaying on cf console nor in loggregator

### ISSUE THREAD

**Issue by ishwar1987** [cloudfoundry/binary-buildpack#5] opened 2016-12-23 07:21 UTC
Hi,
I have developed the sample .net Application(visual studio 2015).  I have use following code.
console.writeln("message");

The above command printing on STDOUT. But its not displaying on cf console nor in loggregator.

Like same if i will use the System.out.println() in java application with different buildpack then its printing on cf console.

Does this bug in binary buildpack?

I am using following cf and buildpack version.
 Cloud Foundry version: cf -v247
binary_buildpack=v1.0.5

Thanks in advanced.

**Comment by sesmith177** [comment] 2017-01-03 20:55
@ishwar1987 if your app writes to STDOUT it should be picked up by the cf logs.

It is unlikely that there is a bug in the binary buildpack, as the buildpack does not modify the application directory.

Can you show us the staging / application logs that you do have?

Thanks.

**Comment by sesmith177** [comment] 2017-01-10 16:55
@ishwar1987 it looks like this is a duplicate of https://github.com/cloudfoundry/dotnet-core-buildpack/issues/129, so we will close this one and continue the investigation in 129.

**Closed by sesmith177** 2017-01-10 16:55 UTC
Labels: unscheduled

**Comment by MaheshRudrachar** [comment] 2017-04-07 01:43
This issue seems different from what is marked as duplicate!!!

@ishwar1987 does this bug (buildpack does not modify the application directory) resolved in latest version of binary_buildpack?

**Comment by sclevine** [comment] 2017-04-20 13:59
Neither this issue nor https://github.com/cloudfoundry/dotnet-core-buildpack/issues/129 are bugs. Neither buildpack supported Windows cells when these issues were open.

The latest release of the binary buildpack now does support Windows cells.
