### ISSUE TITLE
Binary Buildpack fails with "No such file or directory"

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry/binary-buildpack#79] opened 2022-03-09 17:38 UTC
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`)?
`cf version 8.2.0+fd8fbca64.2022-02-09`

What version of the buildpack you are using?
`binary_buildpack        cflinuxfs3   true      false    binary_buildpack-cflinuxfs3-v1.0.42.zip`

If you were attempting to accomplish a task, what was it you were attempting to do?
I'm trying to push a golang binary using the buildpack

What did you expect to happen?
The app to run

What was the actual behavior?
Failed with "No such file or directory"

To reproduce:
1. clone https://github.com/cloudfoundry/loggregator-tools/
2. cd `loggregator-tools/constlogger`
3. `go build` (on linux)
4. `cf push constlogger-1000-256 -b binary_buildpack -c 'ls -la && cat ./constlogger.go && ./constlogger'`

Logs:
```
2022-03-09T10:13:29.62-0700 [APP/PROC/WEB/0] OUT total 6316
2022-03-09T10:13:29.62-0700 [APP/PROC/WEB/0] OUT drwxr-xr-x 1 vcap vcap      75 Mar  9 17:13 .
2022-03-09T10:13:29.62-0700 [APP/PROC/WEB/0] OUT drwx------ 1 vcap vcap      93 Mar  9 17:13 ..
2022-03-09T10:13:29.62-0700 [APP/PROC/WEB/0] OUT -rwxr-xr-x 1 vcap vcap 6454914 Mar  9 17:13 constlogger
2022-03-09T10:13:29.62-0700 [APP/PROC/WEB/0] OUT -rw-r--r-- 1 vcap vcap    1632 Mar  7 17:14 constlogger.go
2022-03-09T10:13:29.62-0700 [APP/PROC/WEB/0] OUT -rw-r--r-- 1 vcap vcap     118 Mar  7 17:16 go.mod
2022-03-09T10:13:29.62-0700 [APP/PROC/WEB/0] OUT -rw-r--r-- 1 vcap vcap    1229 Mar  7 17:16 go.sum
2022-03-09T10:13:29.63-0700 [APP/PROC/WEB/0] OUT // tool for generating log load
2022-03-09T10:13:29.63-0700 [APP/PROC/WEB/0] OUT // usage: gets settings from application name
2022-03-09T10:13:29.63-0700 [APP/PROC/WEB/0] OUT // If pushed as just `constlogger`, emits 1000 logs per second
2022-03-09T10:13:29.63-0700 [APP/PROC/WEB/0] OUT // If pushed as, e.g., `constlogger-100`, emits 100 logs per second
2022-03-09T10:13:29.63-0700 [APP/PROC/WEB/0] OUT // If pushed as, e.g., `constlogger-100-50`, emits 100 logs per second that are each 50 bytes long (including the newline)
<rest of constlogger.go redacted for brevity> ...
2022-03-09T10:13:29.63-0700 [APP/PROC/WEB/0] ERR bash: ./constlogger: No such file or directory
```

Notes: `ls` and `cat` work fine but executables can't be found

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by brayanhenao** [comment] 2022-03-22 20:21
Hi, @MasslessParticle

I performed the steps you mentioned but could not reproduce the error. When uploading the application to CF it does not present any problem.

Steps that I used to reproduce the error:

1. `git clone git@github.com:cloudfoundry/loggregator-tools.git`
2. `cd loggregator-tools/constlogger`
3. `env GOOS=linux GOARCH=amd64 go build`
4. `cf push constlogger-1000-256 -b binary_buildpack -c 'ls -la && cat ./constlogger.go && ./constlogger'`

Results:

```
Staging app and tracing logs...
   Downloading app package...
   Downloaded app package (3.5M)
   -----> Binary Buildpack version 1.0.42
   Exit status 0
   Uploading droplet, build artifacts cache...
   Uploading droplet...
   Uploading build artifacts cache...
   Uploaded build artifacts cache (214B)
   Uploaded droplet (3.5M)
   Uploading complete
   Cell f1a3486a-97ac-491b-b4ed-2e229ff6fc22 stopping instance c6f92400-f3d6-42eb-922f-14b279c55f7f
   Cell f1a3486a-97ac-491b-b4ed-2e229ff6fc22 destroying container for instance c6f92400-f3d6-42eb-922f-14b279c55f7f
   Cell f1a3486a-97ac-491b-b4ed-2e229ff6fc22 successfully destroyed container for instance c6f92400-f3d6-42eb-922f-14b279c55f7f

Waiting for app to start...

name:              constlogger-1000-256
requested state:   started
routes:            constlogger-1000-256.prune.cf-app.com
last uploaded:     Tue 22 Mar 16:12:17 EDT 2022
stack:             cflinuxfs3
buildpacks:        binary

type:            web
instances:       1/1
memory usage:    1024M
start command:   ls -la && cat ./constlogger.go && ./constlogger
     state     since                  cpu    memory   disk     details
#0   running   2022-03-22T20:12:24Z   0.0%   0 of 0   0 of 0
```
CF Apps
```
❯ cf apps
Getting apps in org system / space my-space as admin...
OK

name                   requested state   instances   memory   disk   urls
constlogger-1000-256   started           1/1         1G       1G     constlogger-1000-256.prune.cf-app.com
```

Did you try to reproduce the error more than once?

**Comment by ryanmoran** [comment] 2023-02-17 16:27
Closing because we don't have anymore information on it. If it's still an issue, please re-open/file a new issue.

**Closed by ryanmoran** 2023-02-17 16:27 UTC
